Ruby Enumerable Methods
cgcarlosg/Enumerables pull request #1
Opened 2020-11-17 15:48 UTC by brenoxav

We reimplemented Ruby's enumerable methods using yield and proc.

2020-11-17 18:31 UTC, Georjane requested changes
## Status: Changes Required 🛑 ❌ 
### Hi Team @brenoxav  and @cgcarlosg 🙌🙌
Nice work on the enumerable methods.👏 I see you have a basic understanding of what each of the methods is supposed to do. But now you have to implement solutions for all possible cases like when a block is given or not, and when the method is called on a range, a hash, or an array.🚫
- ### my_each method

For example:

`a = [ "a", "b", "c" ]`
`puts a.each`

returns `#<Enumerator:0x0000000002360f40>`

but your my_each method,

`puts a.my_each` 

returns the following error message


![errors](https://user-images.githubusercontent.com/60772732/99428098-7c7c5e00-2906-11eb-9d39-6bbcee3c8a0e.png)


- [x] Normally, Enumerables `#each` returns an Enumerator if no block is given. But your `#my_each` throws an error when no block is given. 
- [x] Enumerables` #each` when a block is given when self is a range returns the range itself after calling the given block once for each element in self but your `#my_each` throws an error when called on a range

`a = (1..5)`
`puts a.each{|x| print x, " -- " }` returns  `1 -- 2 -- 3 -- 4 -- 5 --`
but `puts a.my_each{|x| print x, " -- " }` returns an error

- [x] A similar case for Enumerables `#each` when a block is given when self is a range calls the given block once for each element in self

- [x] Normally, Enumerables` #my_each` when a block is given when self is a hash behaves like #each calls the given block once for each element in self but your method doesn't work like this.
- ### my_each_with_index method

- [x] it should return an enumerator if no block is given

- [x] when a block is given when self is a range, it should return the range itself after calling the given block once for each element in self

- [ ]  when a block is given when self is a range it should behave like `#each_with_index` which calls the given block once for each element in self

- [ ] when a block is given when self is a hash it should behave like `#each_with_index` which calls the given block once for each element in self

- ### my_select method

- [ ] it should return an array containing all elements of enum for which the given block returns a true value::range

- ### my_all, my_any, my_none methods

- [ ] it should return false if the block returns false or nil::range

- [ ] when no block or argument is given it should return true when none of the collection members are false or nil

- [ ] when no block or argument is given it should return false when one of the collection members is false or nil

- [ ] when a class is passed as an argument it should return true if all of the collection is a member of such class::Integer, class::Numeric

- [ ] when a class is passed as an argument it should return false if any of the collection is not a member of such class

- [ ] when a Regex is passed as an argument it should return true if all of the collection matches the Regex

- [ ] when a pattern other than Regex or a Class is given it should return false if any of the collection does not match the pattern

- ### my_count method

- [ ] it should return the number of items in enum through enumeration

- [ ] it should return the number of items in enum through enumeration::range

- [ ] it should count the number of items in enum that are equal to the item if an argument is given

- ### my_map method
- [ ] it should return a new array with the results of running a given block once for every element in enum::range

- [ ] it should return an Enumerator if no block is given

- ### my_inject method
- [ ]  when a block is given without an initial value it should combine all elements of enum by applying a binary operation, specified by a block::range

- [ ] when a symbol is specified without an initial value it should combine each element of the collection by applying the symbol as a named method

- [ ] when a symbol is specified with an initial value it should combine each element of the collection by applying the symbol as a named method::range

- ### multiply_els method

- [ ] it should accept an array as an argument and multiply all the elements of the array together using #my_inject

Please go through each of the required changes carefully, fix them, and request another code review.
You can find a good resource for the enumerable methods [here](https://ruby-doc.org/core-2.6.5/Enumerable.html) 👍🏽 

Feel free to reach out to me on Slack if you have any questions, **_Witah Georjane_**🤝🤝

Happy Coding and Goodluck.👍👌💻

2020-11-19 07:52 UTC, abredi requested changes
### Status: Require changes  ♲
Hi @cgcarlosg and @brenoxav, I am [Abdulaziz Redi Ali](https://azizali.ml/) your TSE in this project. 👏  ✨ I applaud you for your hard work in implementing custom enumerable methods. Most requirements have done 👌, Kindly fix the following issues.

[REQUIRED]

- [x] 1)  #my_each method should return an Enumerator if no block is given
- [x] 2) #my_each_with_index  should return an enumerator if no block is given
- [x] 3) #my_select should return an enumerator if no block is given
- [ ] 4) #my_all? should return false when one of the collection members are false and when no block or argument is given 
  	E.g. `[1, false, 'hi', []].my_all?`
- [ ] 5) #my_all? should return true when a class is passed as an argument and all of the collection is a member of such class     
	E.g. `[2 ,3, 4].my_all?(Numeric)`     
- [ ] 6) #my_any? Should return true when no block or argument is given and at least one of the collection is not false or nil
     	E.g. `[nil, false, true, []].my_any?`
- [ ] 7) #my_any? should return true when a class is passed as an argument and at least one of the collection is a member of such class
      `[2, 4, 5, 6, 7].my_any?(Numeric)`
- [ ] 8) #my_none? returns false if the block ever returns true for all elements::range
     	`(10..20).none?(proc { |num| num > 19 })`
- [ ] 9) #my_none? should return true none of the collection members is true
 	`[nil, false].my_none?`
- [ ] 10) #my_none? should return false when a pattern other than Regex or a Class is given and only if one of the collection matches the pattern
- [ ] 11) #my_count should return the number of items in enum through enumeration
       E.g. `[1, 2, 3, 4, 5].my_count`  should return 5
- [ ] 12)  #my_count should return the number of items in enum through enumeration::range
      E.g `(1..5).my_count`  should return 5
- [ ] 13) #my_count should count the number of items in enum that are equal to an item if an argument is given
    e.g.  `[6, 6, 2].my_count(6)`
- [ ] 14) when a symbol is specified without an initial value #my_inject should combine each element of the collection by applying the symbol as a named method 
       E.g 
 ```  
[1, 3, 6, 7].my_inject(:+)
(1..5).my_inject(:*)
 [2, 3, 6, 7].my_inject(20, :*)
 (1..5).my_inject(2, :*)
```
- [x] 15) Put the #multiply_els method outside of the Enumerable module
- [ ] 16) Add descriptive content and setup instruction in the readme file

[OPTIONAL]

 - [ ] Enable all rubocop rules

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2020-11-19 18:20 UTC, ebeagusamuel requested changes
# Changes Required :recycle: 
Hello team :wave: 
Nice work you've done so far. Just a few changes to be made to get the project approved.
Please check the comment below and also update your PR message with more information.
Happy coding :+1: 
slack(@ebeagusamuel)

2020-11-19 18:20 UTC, ebeagusamuel commented on enumerables.rb
> +        return false
- [x]  when no block or argument is given, your my_all? should return true when none of the collection members are false or nil. Your code is currently returning false if no block or argument is given.

2020-11-19 18:20 UTC, ebeagusamuel commented on enumerables.rb
> +  end
- [x] your my_none? should return true if the block never returns true for all elements.
- [x] when no block or argument is given, your my_none? should return false only if one of the collection members is true.
- [x] when a pattern other than Regex or a Class is given, your my_none? should return false only if one of the collection matches the pattern.

2020-11-19 18:20 UTC, ebeagusamuel commented on enumerables.rb
> +end
- [ ] when a symbol is specified without an initial value, your my_inject should combine each element of the collection by applying the symbol as a named method. i.e `[1, 2, 3, 4].my_inject(:+)` should return 10.
- [ ]  when a symbol is specified without an initial value, your my_inject should combine each element of the collection by applying the symbol as a named method: range. i.e it should be able to work also on a range(`(1..4).my_inject(:+)` should return 10)
- [ ] when a symbol is specified with an initial value, my_inject combines each element of the collection by applying the symbol as a named method. i.e `[1, 2, 3, 4].my_inject(20, :*)` should return 480 and should also be able to work on a range too.

2020-11-20 00:05 UTC, abredi requested changes
### Status: Require changes  ♲
Hi @cgcarlosg and @brenoxav, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE in this PR. 👏 👏 You made good progress on this project. ✨ I applaud you for your hard work in implementing custom enumerable methods. Most requirements have done 👌, Kindly fix the following issues.

[REQUIRED]

- [ ] If no block or argument is given `#my_all?` should return false when one of the collection members is false or nil
_Example:_
`[nil, true, 99].all?  #=> false` so, `#my_all?` should return the same result as the original method
`[nil, true, 99].my_all?   #=> false`

- [ ] If a block is given with an initial value `#my_inject` should combine all elements of enum by applying a binary operation, specified by a block

   Example:
   `(2..4).inject(2) { |product, n| product * n } #=> 48`

- [ ] If a symbol is specified with an initial value #my_inject should combine each element of the collection by applying the symbol as a named method.

Example using array:
`[2, 3, 4].inject(2, :*)  #=> 48 so`, `#my_inject` should return the same result as the original method
`[2, 3, 4].inject(2, :*)   #=> 48`

Example using range:
`(2..4).inject(2, :*)  #=> 48` so, `#my_inject` should return the same result as the original method
`(2..4).inject(2, :*)   #=> 48`

[OPTIONAL]

- [ ] Enable all rubocop rules
- [ ] Refactor your complex methods(my_all?, my_none?, my_all?) by extracting a code fragment into a new method

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Connect me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2020-11-20 15:21 UTC, ElijahTobs approved these changes
# Status: Approved! :tada: 

Congratulations! @brenoxav and @cgcarlosg 

 Good job implementing the change as requested by the previous TSE.

## [NICE TO HAVE]
- [ ] Add a live demo link of your methods to the README file. You can use [repl](https://repl.it/)
- [ ] Fix the issues link in your README file.

## You can now merge and submit.

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2020-11-20 20:28 UTC, merged